### ISSUE TITLE
missing hdw.dat.svb

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/hdw.dat#5]
The `hdw.dat` file for SPEAR is missing from the this repository.

If you look at [the radars.dat file here](https://github.com/SuperDARN/rst/blob/master/tables/superdarn/radar.dat) it references SPEAR.

However, even the new  [RST repo](https://github.com/SuperDARN/rst/tree/master/tables/superdarn/hdw) doesn't have the hdw.dat.svb file...

So this issue also occurs for official RST. I'll file it there too.

**Comment by asreimer** [comment]
Issue filed at [SuperDARN/rst](https://github.com/SuperDARN/rst/issues/114) too.

**Comment by ksterne** [comment]
As was discussed in the [Data Analysis WG's RST repo](https://github.com/SuperDARN/rst/pull/115), it seems as though there isn't an interest in pulling this file into the main repo since there is very low use case for this file and most of the data in the file isn't useful.  So I think we're good to close this issue here, right?

**Comment by ksterne** [comment]
I should also add that there are two backups of this file, one exists in the [SuperDARN rst repo](https://github.com/SuperDARN/rst/releases/tag/v3.5) and the other exists in the [VTSuperDARN rst repo](https://github.com/vtsuperdarn/VTRST3.5).
